### ISSUE TITLE
Content of Pie Chart app goes in another app

### ISSUE THREAD

**Issue by Padlina** [nie-ine/nieOS#59] opened 2018-10-24 07:56 UTC
When you open the Bar Chart open after opening another app, the content (the image of the bar chart) goes in the already open app, and the container is empty.

To reproduce:
- http://localhost:4200/arbeitsflaeche
- from left side panel, add 1) Bar Chart and then 2) Pie chart
- then open Bar chart and after open Pie chart

This problem seems to apply only to Pie Chart and Radial Bar Chart.

**Comment by janCstoffregen** [comment] 2018-10-24 08:17
Duplicate of #43

**Closed by janCstoffregen** 2018-10-24 08:17 UTC
